service: github-stats

provider:
  name: aws
  runtime: nodejs6.10
  profile: playpen
  region: ap-southeast-2
  environment:
    VERBOSE: ${file(./serverless.env.yml):VERBOSE}
    REPOS: ${file(./serverless.env.yml):REPOS}
    ACCESS_TOKEN: ${file(./serverless.env.yml):ACCESS_TOKEN}
    DB_HOST: ${file(./serverless.env.yml):DB_HOST}
    DB_USER: ${file(./serverless.env.yml):DB_USER}
    DB_PASSWORD: ${file(./serverless.env.yml):DB_PASSWORD}
    DB_NAME: ${file(./serverless.env.yml):DB_NAME}

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

functions:
  githubStats:
    handler: handler.main
    events:
      - schedule: rate(5 minutes)
